### ISSUE TITLE
Cheat Sheet bug

### ISSUE THREAD

**Issue by tenkrux** [end-4/dots-hyprland#1559]
### Step 1. Before you submit

- [x] I have read the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/ii-qs/04troubleshooting/) and [Usage](https://end-4.github.io/dots-hyprland-wiki/en/ii-qs/02usage/) pages.
- [x] I've successfully updated to the latest version following the [guidance](https://end-4.github.io/dots-hyprland-wiki/en/ii-qs/01setup/#updating).
- [x] I've successfully updated the system packages to the latest.
- [ ] I've ticked the checkboxes without reading their contents

### Step 2. Quick diagnose info

<details><summary>Quick diagnose</summary>

```
<!-- Run `./diagnose` inside the repo, and paste the result here! --> since I’m on phone I can’t really do it
```

</details>

### Step 3. Describe the issue

 hello I was just setting up my arch Linux first it was working but it suddenly stopped working idrk why I looked at everything but still can’t found the problem if anyone has any idea why or what could make this look like that please tell me 

![Image](https://github.com/user-attachments/assets/19eef403-23a5-41fc-9c94-366f20db4811)
![Image](https://github.com/user-attachments/assets/784fbe18-9bd2-464d-ba29-07c3d2a17250)

<details><summary>Logs</summary>

```
<!-- Put your log content here!--> same with this
```

</details>

### Reminder

- [x] I agree that it's usually impossible for others to help me without my logs.

**Comment by tenkrux** [comment]
Btw I found out I have no thing such as “eww” idrk what is it but the Gemini 2.5 pro said it is the reason I’m a new to Linux so I couldn’t really understand it

**Comment by sasinhe** [comment]
I second that, just installed the config and mine cheat sheet is empty too

![Image](https://github.com/user-attachments/assets/ed0ce0ca-518d-4013-a174-0428fc9eb0b1)

**Comment by kaydrz1** [comment]
same

**Comment by wxguy** [comment]
Me too...

**Comment by AkselGlyholt** [comment]
I have the same issue

**Comment by AmiyoKm** [comment]
Same issue

**Comment by Neliq** [comment]
same

**Comment by Manunyo** [comment]
+1  - fresh install on Endeavour OS base.

**Comment by AkselGlyholt** [comment]
Just reinstalled a couple of moments ago, and now it seems to be working again.

**Comment by TheSamG** [comment]
Yup, a full reinstall fixed the issue for me as well

**Comment by pvzh82** [comment]
same

**Comment by SombrathnaSout** [comment]
anyone found a fix without to reinstall?

**Comment by tenkrux** [comment]
Guys, I reinstalled it but this time with endevaour Os and it just fixed everything! Turns out arch wasn’t the best choice for this dot file

**Comment by AkselGlyholt** [comment]
Works perfectly fine on my Arch installation. But as I commented earlier, it seemed to work a little later with a simple reinstallation. So I think no matter what OS you're using it will work fine now.

**Comment by SohanSriData** [comment]
By fresh install, do u mean u ran the install script again after deleting the original dots-hyprland directory, or is there anything else i need to do?

**Comment by wxguy** [comment]
> By fresh install, do u mean u ran the install script again after deleting the original dots-hyprland directory, or is there anything else i need to do?

He meant that only. But it didn't work for me. Moved config directory and reinstalled the end4 config. Issue remain same. 

There are lot of people commenting on this issue. This needs to be addressed soon.

**Comment by oooo-cyber** [comment]
@wxguy 

Here's what I did to fix the cheatsheet keybinds tab issue without fresh install as it didn't work for me:

## ⚠️WARNING⚠️ This fix was tested on NixOS where the `.config/quickshell/ii/scripts/hyprland/get_keybinds.py` shebang is 
### `#!/usr/bin/env python3` 
## not 
### `#!/usr/bin/env -S\_/bin/sh\_-c\_"source\_\$(eval\_echo\_\$ILLOGICAL_IMPULSE_VIRTUAL_ENV)/bin/activate&&exec\_python\_-E\_"\$0"\_"\$@""`
## So I have no guarantee that this fix will work in other distros.

## Fix for Cheatsheet Keybinds Tab Not Working

### The issue:
In `.config/quickshell/ii/services/HyprlandKeybinds.qml`, there was a trailing comma in the command array that was causing problems:

```qml
// Problem code
command: [root.keybindParserPath, "--path", root.defaultKeybindConfigPath,]
```

### The fix:
Remove the trailing comma from the command array:

```qml
// Fixed code
command: [root.keybindParserPath, "--path", root.defaultKeybindConfigPath]
```

### Steps to implement:
1. Open the file: `.config/quickshell/ii/services/HyprlandKeybinds.qml`
2. Locate the `Process` with id `getDefaultKeybinds`
3. Find the command array with the trailing comma
4. Remove the trailing comma after `root.defaultKeybindConfigPath`
5. Save the file
6. Quickshell will be reloaded and keybinds tab works perfectly

This small syntax fix ensures the Python script receives the correct arguments, allowing it to properly parse the keybind configurations and populate the cheatsheet's keybinds tab.

<img width="1409" height="875" alt="Image" src="https://github.com/user-attachments/assets/63794814-e9b0-472b-95c3-975db713a09c" />

**Comment by end-4** [comment]
i implemented the fix. @tenkrux is it working now?

**Comment by SohanSriData** [comment]
@end-4  I tried reinstalling after the trailing comma commit. The buttons for elements and keybinds are now visible. Keybinds still not visible. I am guessing theres a problem with the keybind parser

<img width="392" height="207" alt="Image" src="https://github.com/user-attachments/assets/358ae3f4-b9a6-4009-9a9f-d690b96ae704" />

<img width="1248" height="799" alt="Image" src="https://github.com/user-attachments/assets/7991cfca-2124-445b-b169-b8c76d7fc424" />

**Comment by oooo-cyber** [comment]
@SohanSriData Have You tried to run the

`.config/quickshell/ii/scripts/hyprland/get_keybinds.py ` manually to check if there is output or not ?

In my case there was no output until I used the system python env shebang instead illogical-impulse venv (I think NixOS cant run the script proberly  with illogical-impulse venv)

kindly send the result of 
`python ~/.config/quickshell/ii/scripts/hyprland/get_keybinds.py --path ~/.config/hypr/hyprland/keybinds.conf`

**Comment by SohanSriData** [comment]
@oooo-cyber  Here's the output. I dunno but it seems to be outputting what it should

<img width="1884" height="1006" alt="Image" src="https://github.com/user-attachments/assets/9a343a67-d018-4f5b-8054-ae455ffec49d" />

**Comment by oooo-cyber** [comment]
@SohanSriData The output is correct. @end-4 What else could be causing this issue?

**Comment by ddiegosr** [comment]
Just to mention, I had this problem some days ago, before the trailing comma commit even with fresh install the keybinds stayed broken, but after a fresh install yesterday (for other reasons) and installing the dotfiles with the trailing comma commit, the keybinds are back working.

@SohanSriData how did you updated the dotfiles? Was it manually, or using the update script, or just pulling new changes from the repo and running the install script again? Maybe this can influence the fix

**Comment by SohanSriData** [comment]
@ddiegosr  I used the uninstall script, deleted the dots-hyprland directory and then cloned the repo again and used the install script.

**Comment by CastiloVitae** [comment]
Hello.
I did this, checked the `.config/quickshell/ii/services/HyprlandKeybinds.qml` just in case there was the trailing comma (there was none).

But, the keybinds were still empty just like 

> [@end-4](https://github.com/end-4) I tried reinstalling after the trailing comma commit. The buttons for elements and keybinds are now visible. Keybinds still not visible. I am guessing theres a problem with the keybind parser
> <img alt="Image" width="392" height="207" src="https://private-user-images.githubusercontent.com/155820758/467072815-358ae3f4-b9a6-4009-9a9f-d690b96ae704.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTM2MTI5NjYsIm5iZiI6MTc1MzYxMjY2NiwicGF0aCI6Ii8xNTU4MjA3NTgvNDY3MDcyODE1LTM1OGFlM2Y0LWI5YTYtNDAwOS05YTlmLWQ2OTBiOTZhZTcwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDcyN1QxMDM3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NjIyYTA4Mjg2YTFiNjRmNzg2YTk2YjA2MDFkYjY5YTk0ZTQzNmUyYzhjN2M0NThmYTM5NDBiMmI0YmQ4YjE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4Qgki8SJM8t1hA2pbipOW-fhVjTGopM12_bwCYKJVIU"> <img alt="Image" width="1248" height="799" src="https://private-user-images.githubusercontent.com/155820758/467073029-7991cfca-2124-445b-b169-b8c76d7fc424.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTM2MTI5NjYsIm5iZiI6MTc1MzYxMjY2NiwicGF0aCI6Ii8xNTU4MjA3NTgvNDY3MDczMDI5LTc5OTFjZmNhLTIxMjQtNDQ1Yi1iMTY5LWI4Yzc2ZDdmYzQyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDcyN1QxMDM3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjJmZmZmNGM1OTVmZGFkMDYzYWE2N2IwNDBkMmYxYWM0ZjBhYzgzZDM3NTc5NmE4MWRhNjc2ODlhMjc2MzZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fHY70veFtIOMgnmeh_SxBmCI2NeVjPT6K-NxDEZV0lg">

Oh, I must say that I have changed the cheat sheet keybind to Super + Space, since the default one was not working with my keyboard.


**EDIT:** Apparently after following the "Update" from [https://end-4.github.io/dots-hyprland-wiki/en/ii-qs/01setup/](url) (i use arch btw) and changing the keybind once more, it works like it should.
As shown here: 

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/f0c74753-a2b3-4052-a80a-abfae15ce352" />

**Comment by auggie246** [comment]
bug still persist

when running `qs log --path .config/quickshell/ii/shell.qml` I am getting 
```
  WARN: Process failed to start, likely because the binary could not be found. Command: QList("/hyprland/get_keybinds.py", "--path", "/home/<user>/.config/hypr/custom/keybinds.conf")
  WARN: Process failed to start, likely because the binary could not be found. Command: QList("/hyprland/get_keybinds.py", "--path", "/home/<user>/.config/hypr/hyprland/keybinds.conf")
```

which leads me to `.config/quickshell/ii/services/HyprlandKeybinds.qml` and the following line causing issues

`property string keybindParserPath: FileUtils.trimFileProtocol(`${Directories.scriptPath}/hyprland/get_keybinds.py`)`

`${Directories.scriptPath}` is somehow not referenced properly as when i hard code it to `.config/quickshell/ii/scripts`, cheatsheet now works


EDIT: Issue has been resolved after updating to 0.2.0, not sure if it's related but at least it's working now

**Comment by end-4** [comment]
Looks to me this is because I switched `Quickshell.configPath` to `Quickshell.shellPath` and an update of Quickshell was necessary for that `shellPath` func to be available. Did it say anything like shellPath not found or undefined is not a function?

**Comment by Saint2999** [comment]
<img width="1737" height="109" alt="Image" src="https://github.com/user-attachments/assets/0e659fc4-7421-4a5c-ac0c-ea26cc918b92" />

**Comment by Saint2999** [comment]
@end-4 currently everything that uses Quickshell.shellPath in the code doesn't work

for example, screenshot UtilButton
...
onClicked: Quickshell.execDetached(["qs", "-p", **Quickshell.shellPath("screenshot.qml")**])
...

**Comment by end-4** [comment]
> currently everything that uses Quickshell.shellPath in the code doesn't work

`yay -S quickshell-git`

**Comment by dev-abderrahim** [comment]
fixed, and I also suggest to make the cheat sheet scale automatically or something to prevent the off-screen keymaps on smaller screens. 

as it appears in the screenshot, there some keymaps off the screen at the bottom after and even before adding keymaps

<img width="1366" height="768" alt="Image" src="https://github.com/user-attachments/assets/ef2a40b3-fa5e-4b3c-8b21-52cfc04dd61d" />

**Comment by clsty** [comment]
This issue is somehow outdated, but in #1635 and #2319 it appears again. For #2319 it seems to be caused by user not having python venv installed though.
